const app = document.querySelector("#app");
const API_URL = "https://script.google.com/macros/s/AKfycbyJ0eRDfjHPulR9tqv-yvtEy_NvOXPEUeJvYIkMrKUc_3r9Z6qseP9Mni2TkKoOqxTx/exec";
const RESULTADOS = "desempenho_resultados";
const RASCUNHO = "desempenho_rascunho_v2";
const FLUXO = ["CONHECER", "ANALISAR", "DECIDIR", "JUSTIFICAR", "PLANEJAR", "LIDERAR"];
let banco, participantesDisponiveis = [], etapa = -1, etapaSalva = 0, participante = "", serie = "", turma = "", inicio = 0, respostas = {}, finalizado = false;

const itensSmart = [
  { id: "specific", campo: "Específica", texto: "Combinar o envio de uma atualização antes de cada reunião semanal.", explicacao: "Específica indica com clareza qual comportamento será realizado." },
  { id: "measure", campo: "Mensurável", texto: "Enviar as 8 atualizações previstas e avisar sobre riscos em até 1 dia útil.", explicacao: "Mensurável apresenta números ou indicadores que permitem conferir o resultado." },
  { id: "achievable", campo: "Atingível", texto: "Usar um modelo de atualização e receber orientação da liderança a cada 15 dias.", explicacao: "Atingível considera os recursos e o apoio disponíveis para realizar a meta." },
  { id: "relevant", campo: "Relevante", texto: "Ajudar a equipe a antecipar riscos e organizar os prazos das entregas.", explicacao: "Relevante mostra por que o comportamento importa para o trabalho." },
  { id: "time", campo: "Temporal", texto: "Acompanhar a meta durante 60 dias e revisar o resultado ao final.", explicacao: "Temporal define o período ou prazo para realizar e revisar a meta." },
  { id: "action", campo: "Ação do PDI", texto: "Praticar com o modelo, registrar dúvidas e pedir feedback nos encontros quinzenais.", explicacao: "A ação do PDI descreve uma atividade concreta para desenvolver a habilidade." }
];

const desafios = [
  { titulo: "Contrato de avaliação", contexto: "CAND-027 está há três meses na equipe. Antes de atribuir uma nota, você precisa estabelecer um processo justo.", descritor: "Finalidade e critérios", tipo: "select", prompt: "Qual deve ser o primeiro passo do ciclo?", opcoes: [["criteria", "Combinar objetivo, critérios observáveis e período com a colaboradora."], ["punish", "Definir uma nota com base na impressão geral do gestor."], ["rank", "Comparar CAND-027 com a pessoa mais experiente da equipe."]], correto: "criteria", feedback: "Critérios conhecidos, período definido e diálogo dão previsibilidade e propósito formativo à avaliação.", consequencias: { criteria: "Expectativas compartilhadas; a colaboradora sabe como será avaliada.", punish: "A nota surpresa tende a reduzir confiança e não indica como melhorar.", rank: "A comparação ignora diferenças de experiência e critérios do cargo." } },
  { titulo: "Sala de evidências", contexto: "No trimestre: 18 de 20 solicitações concluídas no prazo; 96% de registros sem retrabalho; duas atualizações de equipe foram enviadas após o combinado. Uma ocorrência recente não representa todo o período.", descritor: "Leitura de evidências e vieses", tipo: "select", prompt: "Qual análise evita melhor erro de recência e efeito halo?", opcoes: [["balanced", "Separar indicadores por critério, conferir a série do trimestre e ouvir fontes pertinentes."], ["recent", "Dar peso decisivo à última atualização atrasada."], ["halo", "Transformar o bom domínio técnico em nota alta para todos os critérios."]], correto: "balanced", feedback: "Amostra distribuída no tempo e critérios independentes reduzem recência e halo. Indicadores precisam de contexto, não de generalizações.", consequencias: { balanced: "Uma série temporal e critérios separados deixam o diagnóstico mais confiável.", recent: "A recência distorce o trimestre inteiro e pode apagar resultados consistentes.", halo: "O efeito halo esconde a lacuna de comunicação sob a impressão técnica positiva." } },
  { titulo: "Mapa de competências", contexto: "Evidências: domina planilhas e conferência de documentos; conhece rotinas de arquivo; executa tarefas com qualidade; precisa antecipar dúvidas e comunicar riscos de prazo.", descritor: "Análise CHA", tipo: "select", prompt: "Qual leitura CHA orienta melhor o desenvolvimento?", opcoes: [["cha", "Conhecimento: rotinas; habilidade: planilhas e conferência; atitude observável a desenvolver: comunicação proativa."], ["personality", "A dificuldade prova que CAND-027 não tem perfil para a função."], ["technical", "Considerar somente o domínio de planilhas, pois atitudes não podem ser observadas."]], correto: "cha", feedback: "CHA integra conhecimentos, habilidades e atitudes demonstradas em contexto. Descreva comportamentos observáveis, sem rotular personalidade.", consequencias: { cha: "O plano desenvolve comportamento concreto sem desconsiderar o domínio técnico existente.", personality: "Um rótulo de personalidade transforma uma habilidade desenvolvível em julgamento fixo.", technical: "Ignorar a comunicação mantém sem resposta a necessidade identificada no caso." } },
  { titulo: "Conversa de desempenho", contexto: "Você vai conversar sobre as atualizações atrasadas e também reconhecer qualidade e cooperação. A colaboradora deve participar da análise.", descritor: "Feedback baseado em evidências", tipo: "select", prompt: "Como abrir a conversa de forma construtiva?", opcoes: [["fact", "Descrever duas situações e seus impactos, ouvir a perspectiva dela e combinar um próximo passo."], ["label", "Dizer que ela é desorganizada e exigir mudança imediata."], ["avoid", "Falar apenas dos pontos positivos e omitir a lacuna observada."]], correto: "fact", feedback: "Fato, impacto, escuta e acordo tornam a conversa específica e respeitosa. Rótulos geram defensividade; omissões impedem aprendizagem.", consequencias: { fact: "A conversa equilibra evidências e escuta, criando um acordo que pode ser acompanhado.", label: "O rótulo pode gerar defensividade e não explica qual comportamento precisa mudar.", avoid: "Sem abordar a lacuna, a colaboradora não recebe oportunidade de agir sobre ela." } },
  { titulo: "Plano de evolução", contexto: "CAND-027 entrega registros com qualidade, mas algumas atualizações chegaram depois do combinado. Ela precisa avisar a equipe sobre o andamento e antecipar riscos de prazo.", descritor: "Meta SMART e PDI", tipo: "smart", prompt: "Leia cada frase e selecione o campo que ela representa. A meta SMART organiza o resultado esperado; o PDI indica uma ação para desenvolver a habilidade.", feedback: "SMART ajuda a deixar a meta clara e acompanhável. O PDI transforma o desenvolvimento em uma ação prática." },
  { titulo: "Liderança em ação", contexto: "A equipe tem experiência, mas precisa melhorar a antecipação de riscos. CAND-027 pediu oportunidades de participar e receber retorno sobre suas apresentações.", descritor: "Liderança, engajamento e parecer", tipo: "lead", prompt: "Escolha uma postura e registre seu parecer final de gestor.", feedback: "Autonomia com combinados e acompanhamento, reconhecimento específico e voz do colaborador sustentam engajamento e responsabilidade compartilhada." }
];

function lerLista(chave) { try { const x = JSON.parse(localStorage.getItem(chave) || "[]"); return Array.isArray(x) ? x : []; } catch { return []; } }
function esc(s = "") { return String(s).replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c])); }
function progresso() { const pct = etapa < 0 ? 0 : Math.round(((etapa + 1) / FLUXO.length) * 100); document.querySelector("#progressText").textContent = etapa < 0 ? "Identificação" : `${FLUXO[etapa]} • S${21 + etapa} de 26`; document.querySelector("#progressBar").style.width = `${pct}%`; }
async function carregar() { try { const [r, nomes] = await Promise.all([fetch("dados/cenarios.json"), fetch("dados/participantes.json")]); if (!r.ok || !nomes.ok) throw Error("dados"); banco = await r.json(); participantesDisponiveis = (await nomes.json()).participantes; restaurarRascunho(); renderIdentificacao(); } catch { app.innerHTML = '<section class="hero"><h1>Não foi possível carregar os dados.</h1><p>Verifique a publicação do simulador.</p></section>'; } }
function restaurarRascunho() { try { const x = JSON.parse(localStorage.getItem(RASCUNHO)); if (x && x.colaborador === banco.colaborador.id) { participante = x.participante || ""; serie = x.serie || ""; turma = x.turma || ""; etapaSalva = Number.isInteger(x.etapa) && x.etapa >= 0 ? x.etapa : 0; respostas = x.respostas || {}; inicio = x.inicio || 0; } } catch {} }
function persistir() { etapaSalva = Math.max(0, etapa); try { localStorage.setItem(RASCUNHO, JSON.stringify({ colaborador: banco.colaborador.id, participante, serie, turma, etapa: etapaSalva, respostas, inicio })); } catch {} }
function renderIdentificacao() {
  etapa = -1; progresso(); const c = banco.colaborador;
  app.innerHTML = `<section class="hero"><span class="eyebrow">Missão de gestão • ${esc(c.id)}</span><h1>Desempenho se constrói com evidências</h1><p>Assuma a gestão do ciclo de CAND-027. Analise o contexto, tome decisões justificadas, planeje o desenvolvimento e lidere o acompanhamento.</p><div class="flow">${FLUXO.map((x, i) => `<span>${i + 1}. ${x}</span>`).join("")}</div><div class="grid"><article class="card"><span class="tag">Caso fictício</span><h3>${esc(c.nome)}</h3><p>${esc(c.cargo)} • ${esc(c.tempoEmpresa)}</p><p>${esc(c.historico)}</p></article><article class="card"><span class="tag">Sua missão</span><h3>Decisão profissional</h3><p>Indicadores, relatos e escolhas têm consequências no parecer e no plano final.</p></article><article class="card"><span class="tag">Avaliação formativa</span><h3>Descritores transparentes</h3><p>Veja o resultado por etapa e revise suas produções antes de concluir.</p></article></div><div class="notice">Seu progresso e relatório ficam salvos neste navegador e podem ser consultados pelo professor. Selecione seu nome para começar.</div><div class="card" style="margin-top:20px"><h3>Identificação do participante</h3><div class="field"><label for="nome">Nome do participante</label><select id="nome" onchange="document.querySelector('#erroIdentificacao').textContent=''"><option value="">Selecione seu nome</option>${participantesDisponiveis.map(n => `<option value="${esc(n)}" ${participante === n ? "selected" : ""}>${esc(n)}</option>`).join("")}</select><div id="erroIdentificacao" class="muted" role="alert"></div></div><div class="grid"><div class="field"><label for="serie">Série</label><select id="serie" onchange="sincronizarTurmaPorSerie()"><option value="2ª série – Ensino Médio" ${(serie || "2ª série – Ensino Médio") === "2ª série – Ensino Médio" ? "selected" : ""}>2ª série – Ensino Médio</option><option value="3ª série – Ensino Médio" ${serie === "3ª série – Ensino Médio" ? "selected" : ""}>3ª série – Ensino Médio</option></select></div><div class="field"><label for="turma">Turma</label><select id="turma" onchange="sincronizarSeriePorTurma();document.querySelector('#erroIdentificacao').textContent=''"><option value="">Selecione sua turma</option><option value="2º AT - Administração" ${turma === "2º AT - Administração" ? "selected" : ""}>2º AT - Administração</option><option value="2º BT - Administração" ${turma === "2º BT - Administração" ? "selected" : ""}>2º BT - Administração</option><option value="3º AT - Administração" ${turma === "3º AT - Administração" ? "selected" : ""}>3º AT - Administração</option></select></div></div></div><div class="actions"><a class="btn secondary" href="professor.html">Painel do professor</a><button class="btn primary" onclick="iniciar()">${inicio ? "Retomar missão" : "Iniciar missão →"}</button></div></section>`;
}
function sincronizarSeriePorTurma() { const t = document.querySelector("#turma").value; const s = document.querySelector("#serie"); if (t === "3º AT - Administração") s.value = "3ª série – Ensino Médio"; else if (t) s.value = "2ª série – Ensino Médio"; }
function sincronizarTurmaPorSerie() { const s = document.querySelector("#serie").value; const t = document.querySelector("#turma"); if (s === "3ª série – Ensino Médio") t.value = "3º AT - Administração"; else if (t.value === "3º AT - Administração") t.value = ""; }
function iniciar() {
  participante = document.querySelector("#nome").value;
  turma = document.querySelector("#turma").value;
  const erro = document.querySelector("#erroIdentificacao");
  if (!participante) { erro.textContent = "Selecione seu nome para continuar."; return; }
  if (!turma) { erro.textContent = "Selecione sua turma para continuar."; return; }
  serie = document.querySelector("#serie").value;
  if (!inicio) inicio = Date.now(); etapa = inicio ? etapaSalva : 0; persistir(); renderEtapa();
}function renderEtapa() { progresso(); const e = banco.etapas[etapa], d = desafios[etapa], key = `s${21 + etapa}`; const qhtml = e.questoes.map((q, idx) => `<div class="card question"><div class="question-number">${esc(q.id)} • conhecimento</div><h3>${esc(q.pergunta)}</h3>${q.opcoes.map(o => `<label class="choice ${respostas[q.id] === o[0] ? "selected" : ""}"><input type="radio" name="${esc(q.id)}" value="${esc(o[0])}" ${respostas[q.id] === o[0] ? "checked" : ""} onchange="selecionar('${esc(q.id)}',this.value)"><strong>${esc(o[0].toUpperCase())}.</strong> ${esc(o[1])}</label>`).join("")}</div>`).join(""); app.innerHTML = `<section class="hero"><div class="stage-head"><div><span class="eyebrow">${FLUXO[etapa]} • ${esc(e.codigo)}</span><h1>${esc(e.titulo)}</h1><p>${esc(e.descricao)}</p></div><span class="tag">Etapa ${etapa + 1}/6</span></div><div class="notice"><strong>Contexto:</strong> ${esc(d.contexto)}</div>${qhtml}<div class="card question"><div class="question-number">Desafio aplicado • ${esc(d.descritor)}</div><h3>${esc(d.prompt)}</h3>${renderDesafio(d, key)}</div><div id="retorno" aria-live="polite"></div><div class="actions"><button class="btn secondary" onclick="voltar()">← ${etapa === 0 ? "Identificação" : "Etapa anterior"}</button><button class="btn primary" onclick="avancar()">${etapa === 5 ? "Concluir e gerar dossiê" : "Salvar e avançar →"}</button></div></section>`; }
function renderDesafio(d, key) { const v = respostas[`${key}_desafio`] || ""; if (d.tipo === "select") return d.opcoes.map(([id, label]) => `<label class="choice ${v === id ? "selected" : ""}"><input type="radio" name="desafio" value="${id}" ${v === id ? "checked" : ""} onchange="decidir('${key}_desafio',this.value)"> ${esc(label)}</label>`).join(""); if (d.tipo === "smart") return `<div class="smart-list">${itensSmart.map((item, i) => { const atual = respostas[`${key}_${item.id}`] || ""; return `<article class="card smart-item"><span class="tag">Frase ${i + 1}</span><p>${esc(item.texto)}</p><div class="field"><label for="${key}_${item.id}">Essa frase corresponde a qual campo?</label><select id="${key}_${item.id}" onchange="classificarSmart('${key}','${item.id}',this.value)"><option value="">Selecione o campo</option>${itensSmart.map(op => `<option value="${op.id}" ${atual === op.id ? "selected" : ""}>${esc(op.campo)}</option>`).join("")}</select></div></article>`; }).join("")}</div><p class="muted">Classifique as seis frases. Você pode mudar suas escolhas antes de avançar.</p>`; return `<div class="field"><label for="lideranca">Decisão de liderança</label><select id="lideranca" onchange="decidir('${key}_lead',this.value)"><option value="">Selecione</option>${[["autonomy", "Delegar a apresentação com objetivo claro e check-in combinado"], ["control", "Revisar cada fala e assumir a apresentação pela colaboradora"], ["laissez", "Delegar sem combinar objetivo nem acompanhamento"]].map(([id,t])=>`<option value="${id}" ${respostas[`${key}_lead`]===id?"selected":""}>${esc(t)}</option>`).join("")}</select></div><div class="field"><label for="dossier">Parecer final do gestor (inclua evidências, ponto forte, desenvolvimento, compromisso e acompanhamento)</label><textarea id="dossier" rows="6" maxlength="1200" placeholder="Escreva seu dossiê do gestor…" oninput="guardar('${key}_dossier',this.value)">${esc(respostas[`${key}_dossier`] || "")}</textarea><small class="muted">Mínimo de 100 caracteres para pontuar o descritor de parecer.</small></div>`; }
function campo(id, label, placeholder, key) { return `<div class="field"><label for="${key}_${id}">${esc(label)}</label><input id="${key}_${id}" maxlength="240" placeholder="${esc(placeholder)}" value="${esc(respostas[`${key}_${id}`] || "")}" oninput="guardar('${key}_${id}',this.value)"></div>`; }
function guardar(k,v) { respostas[k] = v; persistir(); }
function classificarSmart(key,id,v) { guardar(`${key}_${id}`,v); const item=itensSmart.find(x=>x.id===id),correto=v===item.id,escolhido=itensSmart.find(x=>x.id===v)?.campo||""; document.querySelector("#retorno").innerHTML=`<div class="notice" role="status"><strong>${correto?"Isso mesmo!":"Vamos revisar."}</strong> ${correto?esc(item.explicacao):`Essa frase corresponde a <strong>${esc(item.campo)}</strong>. Você selecionou ${esc(escolhido)}. ${esc(item.explicacao)}`}</div>`; }
function selecionar(k,v) { guardar(k,v); const q=banco.etapas[etapa].questoes.find(x=>x.id===k); if(!q)return; const ok=v===q.opcoes.find(x=>x[2]===1)?.[0]; const explicacao=ok?"Sua escolha corresponde ao conceito aplicado nesta situação.":"Releia o critério e as evidências: a alternativa mais adequada está associada à decisão baseada em dados e desenvolvimento."; document.querySelector("#retorno").innerHTML=`<div class="notice"><strong>${ok?"Conceito aplicado":"Ponto para revisar"}:</strong> ${esc(explicacao)}</div>`; }
function efeitoDecisao(i,v) { const d=desafios[i]; if(d.tipo==="select") return d.consequencias?.[v]||d.feedback; return v==="autonomy"?"A colaboradora terá espaço para praticar com objetivo e apoio definidos.":v==="control"?"O controle excessivo reduz autonomia e impede observar a evolução real.":"Sem combinados, a delegação deixa de oferecer suporte e critério de sucesso."; }
function decidir(k,v) { guardar(k,v); const d=desafios[etapa],indice=etapa; const efeito=efeitoDecisao(indice,v); const certo=k.endsWith("_desafio")?v===d.correto:k.endsWith("_lead")?v==="autonomy":false; document.querySelector("#retorno").innerHTML=`<div class="notice"><strong>${certo?"Consequência construtiva":"Consequência provável"}:</strong> ${esc(efeito)} ${k.endsWith("_desafio")?`<br><span class="muted">${esc(d.feedback)}</span>`:""}</div>`; }
function respostasLegiveis() { const out={}; for(const [k,v] of Object.entries(respostas)){let label=k; let texto=String(v); const q=banco.etapas.flatMap(e=>e.questoes).find(x=>x.id===k); if(q){label=q.id;texto=q.opcoes.find(o=>o[0]===v)?.[1]||texto;} else if(k.endsWith("_desafio")){const i=Number(k.match(/s(\d+)_/)[1])-21;label=`${banco.etapas[i].codigo} • ${desafios[i].descritor}`;texto=desafios[i].opcoes?.find(o=>o[0]===v)?.[1]||texto;} else if(k==="s26_lead"){label="S26 • Decisão de liderança";texto={autonomy:"Delegar com objetivo e check-in combinado",control:"Revisar cada fala e assumir a apresentação",laissez:"Delegar sem objetivo ou acompanhamento"}[v]||texto;} else if(k.startsWith("s25_")){const id=k.slice(4),item=itensSmart.find(x=>x.id===id);if(item){label=`S25 • Classificação — ${item.campo}`;texto=`${item.texto} | Classificação escolhida: ${itensSmart.find(x=>x.id===v)?.campo||"Não respondida"}`;}} else if(k==="s26_dossier") label="S26 • Parecer do gestor"; out[label]=texto;} return out; }
function voltar() { if (etapa > 0) etapa--; else { renderIdentificacao(); return; } persistir(); renderEtapa(); }
function validacaoEtapa() { const e = banco.etapas[etapa], d = desafios[etapa], key = `s${21 + etapa}`; const faltam = e.questoes.filter(q => !respostas[q.id]).length; if (faltam) return `Responda às ${faltam} questão(ões) de conhecimento para seguir.`; if (d.tipo === "select" && !respostas[`${key}_desafio`]) return "Escolha uma decisão no desafio aplicado."; if (d.tipo === "smart" && itensSmart.some(x => !respostas[`${key}_${x.id}`])) return "Classifique as seis frases para avançar."; if (d.tipo === "lead" && (!respostas[`${key}_lead`] || String(respostas[`${key}_dossier`] || "").trim().length < 100)) return "Escolha uma postura de liderança e escreva um parecer com pelo menos 100 caracteres."; return ""; }
function avancar() { const erro = validacaoEtapa(); if (erro) { document.querySelector("#retorno").innerHTML = `<div class="notice" role="alert">${esc(erro)}</div>`; return; } if (etapa < 5) { etapa++; persistir(); renderEtapa(); } else renderFinal(); }
function calcular() { let total=0,max=0, descritores={}, porEtapa={}; banco.etapas.forEach((e,i)=>{let pontos=0,possiveis=0; const add=(nome,ok)=>{descritores[nome]={pontos:ok?1:0,max:1,nota:ok?100:0}; pontos+=ok?1:0; possiveis++;}; e.questoes.forEach(q=>add(`${e.codigo} • ${q.id}`,respostas[q.id]===q.opcoes.find(o=>o[2]===1)?.[0])); const key=`s${21+i}`,d=desafios[i]; if(d.tipo==='select') add(`${e.codigo} • ${d.descritor}`,respostas[`${key}_desafio`]===d.correto); if(d.tipo==='smart'){itensSmart.forEach(item=>add(`${e.codigo} • ${item.campo}`,respostas[`${key}_${item.id}`]===item.id));} if(d.tipo==='lead'){add(`${e.codigo} • Liderança`,respostas[`${key}_lead`]==="autonomy");add(`${e.codigo} • Parecer do gestor`,String(respostas[`${key}_dossier`]||"").trim().length>=100);} total+=pontos;max+=possiveis;porEtapa[e.codigo]={pontos,max:possiveis,nota:Math.round(pontos/possiveis*100),descritor:d.descritor}; }); return {total,max,nota:Math.round(total/max*100),porEtapa,descritores}; }
function dadosResultado() { const s=calcular(),efeitos={}; for(let i=0;i<4;i++){const k=`s${21+i}_desafio`,v=respostas[k];if(v)efeitos[`S${21+i}`]=efeitoDecisao(i,v);} if(respostas.s26_lead) efeitos.S26=efeitoDecisao(5,respostas.s26_lead); return {id:`${Date.now()}-${Math.random().toString(36).slice(2,8)}`,data:new Date().toISOString(),participante,serie,turma,colaborador:banco.colaborador.id,total:s.total,max:s.max,nota:s.nota,porEtapa:s.porEtapa,descritores:s.descritores,respostas:{...respostas},producoes:respostasLegiveis(),consequencias:efeitos,dossie:respostas.s26_dossier||"",duracaoMin:Math.max(1,Math.round((Date.now()-inicio)/60000))}; }
function textoRelatorio(r=dadosResultado()) { return `DOSSIÊ DO GESTOR — SIMULADOR DE GESTÃO DE DESEMPENHO\n\nParticipante: ${r.participante}\nSérie/Turma: ${r.serie} • ${r.turma}\nColaboradora fictícia: ${banco.colaborador.id} — ${banco.colaborador.nome}\nData: ${new Date(r.data).toLocaleString("pt-BR")} • Duração: ${r.duracaoMin} min\n\nRESULTADO PEDAGÓGICO: ${r.nota}/100 (${r.total}/${r.max} descritores)\n\nPOR ETAPA\n${Object.entries(r.porEtapa).map(([k,v])=>`${k} — ${FLUXO[Number(k.slice(1))-21]}: ${v.pontos}/${v.max} (${v.nota}/100) • ${v.descritor}`).join("\n")}\n\nCONSEQUÊNCIAS DAS DECISÕES\n${Object.entries(r.consequencias||{}).map(([k,v])=>`${k}: ${v}`).join("\n")}\n\nPONTUAÇÃO POR DESCRITOR\n${Object.entries(r.descritores).map(([k,v])=>`${v.pontos}/${v.max} — ${k}`).join("\n")}\n\nDECISÕES E PRODUÇÕES\n${Object.entries(r.producoes||r.respostas).map(([k,v])=>`${k}: ${v}`).join("\n")}\n\nPARECER DO GESTOR\n${r.dossie}\n\nA pontuação mede os descritores explicitados nesta simulação e não representa avaliação real de pessoas.`; }
async function salvarResultadoGoogle(r) { try { await fetch(API_URL,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({...r,simulador:"desempenho"}),keepalive:true}); } catch (erro) { console.warn("Não foi possível enviar o resultado ao Google Sheets. O resultado local foi preservado.",erro); } }
function renderFinal() { if (finalizado) return; finalizado=true; etapa=5; progresso(); const r=dadosResultado(),lista=lerLista(RESULTADOS); lista.push(r); localStorage.setItem(RESULTADOS,JSON.stringify(lista)); salvarResultadoGoogle(r); localStorage.removeItem(RASCUNHO); const s=calcular(); app.innerHTML=`<section class="hero"><span class="eyebrow">Missão concluída • dossiê ${esc(banco.colaborador.id)}</span><h1>Seu parecer gerencial</h1><div class="score"><div class="score-ring" style="--score:${s.nota*3.6}deg"><b>${s.nota}</b></div><div><div class="metric">${s.total}/${s.max}</div><div class="muted">descritores demonstrados</div></div></div><div class="grid">${Object.entries(s.porEtapa).map(([k,v])=>`<article class="card"><span class="tag">${k} • ${FLUXO[Number(k.slice(1))-21]}</span><h3>${v.nota}/100</h3><p class="muted">${v.pontos}/${v.max} • ${esc(v.descritor)}</p></article>`).join("")}</div><div class="notice"><strong>Próximo passo:</strong> revise descritores abaixo de 100 e use o PDI para orientar uma nova tentativa. Os indicadores do caso são fictícios.</div><h2>Dossiê completo</h2><pre class="report">${esc(textoRelatorio(r))}</pre><div class="actions"><button class="btn secondary" onclick="baixarRelatorio()">Baixar relatório TXT</button><button class="btn secondary" onclick="baixarHTML()">Baixar relatório HTML</button><button class="btn primary" onclick="novaMissao()">Nova simulação</button></div></section>`; }
function baixarArquivo(nome,conteudo,tipo) { const blob=new Blob([conteudo],{type:tipo}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=nome;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000); }
function baixarRelatorio() { const r=lerLista(RESULTADOS).at(-1); baixarArquivo("dossie-gestor-CAND-027.txt",textoRelatorio(r),"text/plain;charset=utf-8"); }
function baixarHTML() { const r=lerLista(RESULTADOS).at(-1),html=`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dossiê do gestor — CAND-027</title><style>body{max-width:900px;margin:40px auto;padding:0 20px;font:16px/1.6 Arial,sans-serif;color:#172033}h1{color:#2457d6}pre{white-space:pre-wrap;background:#f4f7fb;border:1px solid #dfe5ee;border-radius:12px;padding:24px;font:inherit}@media print{body{margin:0;max-width:none}pre{border:0}}</style></head><body><h1>Dossiê do gestor</h1><p>Simulador de Gestão de Desempenho • relatório pedagógico</p><pre>${esc(textoRelatorio(r))}</pre></body></html>`; baixarArquivo("dossie-gestor-CAND-027.html",html,"text/html;charset=utf-8"); }function novaMissao() { etapa=-1;etapaSalva=0;participante="";serie="";turma="";inicio=0;respostas={};finalizado=false;renderIdentificacao(); }
carregar();
